import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { matrix } from "../test/support/endpoint-matrix.mjs";
import { format, resolveConfig } from "prettier";
import assert from "node:assert/strict";
const report = JSON.parse(
  readFileSync(new URL("../docs/qualification-results.json", import.meta.url), "utf8"),
);
const latest = [
  ...new Map(report.cases.map((row) => [row.id.replace(/-attempt\d+$/, ""), row])).values(),
];
const names = [
  ...new Set([...matrix.map((row) => row.name), ...report.cases.map((row) => row.operation)]),
].sort();
const rows = names.map((name) => {
  const samples = latest.filter((row) => row.operation === name);
  return `| \`${name}\` | ${matrix.filter((row) => row.name === name).length} | ${samples.filter((row) => row.status === "passed").length} | ${samples.filter((row) => row.status === "failed").length} | ${samples.filter((row) => row.status === "not-run").length} |`;
});
const counts = Object.fromEntries(
  ["passed", "failed", "not-run"].map((status) => [
    status,
    report.cases.filter((row) => row.status === status).length,
  ]),
);
const current = Object.fromEntries(
  ["passed", "failed", "not-run"].map((status) => [
    status,
    latest.filter((row) => row.status === status).length,
  ]),
);
const text = `# Coverage matrix

Generated by \`npm run coverage:report\` from the executable matrix and live ledger.
Capture series started: ${report.capturedAt}.

## How to read this

- Wire cases assert the actual SDK's method/path/query/body/authentication and input immutability.
- The finite matrix uses candidate chains sol/bsc/base/eth/robinhood/arc/stable,
  required/optional parameter classes, separate boundary cases, and per-method failures.
  A serialized chain string is **not** a claim that the service supports that endpoint/chain.
- Every signed wire case verifies Ed25519 against its actual HTTP bytes; every signed
  method also has required/optional RSA-PSS cases. Financial writes are mocked only.
- Live pass means the SDK accepted that response envelope. It does not establish
  complete domain schemas, chain semantics, exact numeric precision or execution safety.
  Recognized array/list emptiness is exposed as \`summary.rows: 0\`; other objects
  may not have row counts. A pass is not proof that a meaningful trade/holder/order
  was returned.
- Failed live cases replay their expected failure; green CI does not fix those failures.
- Table counts use the latest outcome per intended case; the JSON ledger retains
  earlier attempts, including failures followed by successful retries.
  These counts are not unique supported endpoints.
  No finite suite exhausts arbitrary strings, payloads, clocks or concurrency interleavings.

Live ledger: **${counts.passed} passed / ${counts.failed} failed / ${counts["not-run"]} not run**.
Latest per-case outcomes: **${current.passed} passed / ${current.failed} failed / ${current["not-run"]} not run**.

| Method | Offline wire cases | Live pass | Live fail | Not run |
| --- | ---: | ---: | ---: | ---: |
${rows.join("\n")}

## Remaining gates

Read [qualification-results.json](qualification-results.json) for each exact
case, result and reason. The live route family \`/v1/trade/\` was paused after
429s on more than one read endpoint; this is not a claim that the untouched
routes are unsupported. No order was fabricated to qualify \`queryOrder\`.
Deprecated aliases are tested offline. Financial effects require separate
authorization and are never enabled by this qualification runner.

Live samples cover selected small limits, time windows and actors, not all
filter combinations, all pagination chains, provider maxima or continuous load.
API-key/signing-key expiry and long-running collector behavior remain unqualified.

KOL responses in this capture are trading-activity rows (\`maker\`, \`base_token\`,
amounts), not a pure list of wallet profiles. Wallet discovery uses the observed
\`maker\` field. A list-shaped successful response alone cannot validate its meaning.
`;
const file = fileURLToPath(new URL("../docs/coverage.md", import.meta.url));
const rendered = await format(text, { ...(await resolveConfig(file)), parser: "markdown" });
if (process.argv.includes("--check"))
  assert.equal(readFileSync(file, "utf8"), rendered, "Run npm run coverage:report");
else writeFileSync(file, rendered);
